/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#ifndef EDGER8R_MODELAGGREGATOR_U_H
#define EDGER8R_MODELAGGREGATOR_U_H

#include <openenclave/host.h>

#include "modelaggregator_args.h"

OE_EXTERNC_BEGIN

oe_result_t oe_create_modelaggregator_enclave(
    const char* path,
    oe_enclave_type_t type,
    uint32_t flags,
    const oe_enclave_setting_t* settings,
    uint32_t setting_count,
    oe_enclave_t** enclave);

/**** Trusted function IDs ****/
enum
{
    modelaggregator_fcn_id_enclave_modelaggregator = 0,
    modelaggregator_fcn_id_trusted_call_id_max = OE_ENUM_MAX
};

/**** ECALL marshalling structs. ****/
typedef struct _enclave_modelaggregator_args_t
{
    oe_result_t _result;
    unsigned char*** encrypted_accumulator;
    size_t* accumulator_lengths;
    size_t accumulator_length;
    unsigned char** encrypted_old_params;
    size_t old_params_length;
    unsigned char*** encrypted_new_params_ptr;
    size_t* new_params_length;
} enclave_modelaggregator_args_t;

/**** ECALL prototypes. ****/
oe_result_t enclave_modelaggregator(
    oe_enclave_t* enclave,
    unsigned char*** encrypted_accumulator,
    size_t* accumulator_lengths,
    size_t accumulator_length,
    unsigned char** encrypted_old_params,
    size_t old_params_length,
    unsigned char*** encrypted_new_params_ptr,
    size_t* new_params_length);

/**** Untrusted function IDs. ****/
enum
{

    modelaggregator_fcn_id_untrusted_call_max = OE_ENUM_MAX
};

/**** OCALL marshalling structs. ****/
/* There were no ocalls. */

/**** OCALL prototypes. ****/
/* There were no ocalls. */

OE_EXTERNC_END

#endif // EDGER8R_MODELAGGREGATOR_U_H
