// Include the trusted modelaggregator header that is generated
// during the build. This file is generated by calling the
// sdk tool oeedger8r against the modelaggregator.edl file.
#include "modelaggregator_t.h"

#include <stdio.h>
#include <vector>
#include <numeric>
#include <map>
#include <set>
#include <string>

// Include encryption/decryption and serialization/deserialization headers
#include "../../common/encryption/encrypt.h"
#include "../../common/encryption/serialization.h"

using namespace std;

// This is the function that the host calls. It performs
// the aggregation and encrypts the new model to pass back
void enclave_modelaggregator(unsigned char*** encrypted_accumulator,
            uint32_t* decrypted_accumulator_lengths,
            size_t length, 
            unsigned char** encrypted_old_params, 
            uint32_t decrypted_old_params_length, 
            unsigned char*** encrypted_new_params_ptr)
{
    unsigned char serialized_old_params[decrypted_old_params_length];
    decrypt_bytes(*encrypted_old_params, 
            *(encrypted_old_params + 1), 
            *(encrypted_old_params + 2), 
            decrypted_old_params_length,
            (unsigned char**) &serialized_old_params);

    map<string, vector<double>> params = deserialize(string((const char*) serialized_old_params));

    
    vector<map<string, vector<double>>> accumulator;
    set<string> vars_to_aggregate;

    for (int i = 0; i < length; i++) {
        unsigned char decrypted_accumulator[decrypted_accumulator_lengths[i]];
        decrypt_bytes(*encrypted_accumulator[i],
                *(encrypted_accumulator[i] + 1),
                *(encrypted_accumulator[i] + 2),
                decrypted_accumulator_lengths[i],
                (unsigned char**) &decrypted_accumulator);

        map<string, vector<double>> params = deserialize(string((const char*) decrypted_accumulator));

        for (const auto& pair : params) {
            vars_to_aggregate.insert(pair.first);
        }

        accumulator.push_back(params);
    }

    for (string v_name : vars_to_aggregate) {
        vector<double> n_local_iters;
        vector<vector<double>> vars;

        for (map<string, vector<double>> acc_params : accumulator) {
            if (acc_params.find(v_name) == acc_params.end()) { // these params don't have the variable from client
                continue;
            }

            // Each params map will have an additional key "_contribution" to hold the number of local iterations
            double n_iter = acc_params["_contribution"][0];
            n_local_iters.push_back(n_iter);

            // Weighted using local iterations
            vector<double>& weights = acc_params[v_name];
            for_each(weights.begin(), weights.end(), [&n_iter](double& d) { d *= n_iter; });
            vars.push_back(weights);
        }

        if (n_local_iters.empty()) {
            continue; // Didn't receive this variable from any clients
        }

        vector<double> new_val(vars.size(), 0.0);
        double iters_sum = accumulate(n_local_iters.begin(), n_local_iters.end(), 0);
        for (int i = 0; i < new_val.size(); i++) {
            for (vector<double> weights : vars) {
                new_val[i] += weights[i];
            }
            new_val[i] /= iters_sum;
        }
        params[v_name] = new_val;
    }

    string serialized_new_params = serialize(params);

    unsigned char** encrypted_new_params = new unsigned char*[3 * sizeof(char*)];
    encrypt_bytes((unsigned char*) serialized_new_params.c_str(), serialized_new_params.length(), encrypted_new_params);

    // Need to copy over the encrypted model, IV, and tag over to server size memory
    unsigned char** usr_addr_params = (unsigned char**) oe_host_malloc(3 * sizeof(unsigned char *));
    for (int i = 0; i < 3; i++) {
        size_t item_length = strlen((const char *) encrypted_new_params[i]);
        unsigned char* item = (unsigned char*) oe_host_malloc(item_length * sizeof(unsigned char));
        memcpy((void*) item[i], encrypted_new_params[i], item_length * sizeof(unsigned char));
        memcpy(usr_addr_params[i], item, sizeof(unsigned char *));
    }
    memcpy(usr_addr_params, encrypted_new_params, 3);
    *encrypted_new_params_ptr = usr_addr_params;
}
