/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#include "modelaggregator_t.h"

#include <openenclave/edger8r/enclave.h>

OE_EXTERNC_BEGIN

/**** ECALL functions. ****/

static void ecall_enclave_modelaggregator(
    uint8_t* input_buffer,
    size_t input_buffer_size,
    uint8_t* output_buffer,
    size_t output_buffer_size,
    size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;

    /* Prepare parameters. */
    enclave_modelaggregator_args_t* pargs_in = (enclave_modelaggregator_args_t*)input_buffer;
    enclave_modelaggregator_args_t* pargs_out = (enclave_modelaggregator_args_t*)output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers lie within the enclave. */
    /* oe_is_within_enclave explicitly checks if buffers are null or not. */
    if (!oe_is_within_enclave(input_buffer, input_buffer_size))
        goto done;

    if (!oe_is_within_enclave(output_buffer, output_buffer_size))
        goto done;

    /* Set in and in-out pointers. */
    if (pargs_in->encrypted_accumulator)
        OE_SET_IN_POINTER(encrypted_accumulator, ((size_t)pargs_in->accumulator_length * sizeof(unsigned char**)), unsigned char***);
    if (pargs_in->accumulator_lengths)
        OE_SET_IN_POINTER(accumulator_lengths, ((size_t)pargs_in->accumulator_length * sizeof(size_t)), size_t*);
    if (pargs_in->encrypted_old_params)
        OE_SET_IN_POINTER(encrypted_old_params, ((size_t)3 * sizeof(unsigned char*)), unsigned char**);

    /* Set out and in-out pointers. */
    /* In-out parameters are copied to output buffer. */
    if (pargs_in->encrypted_new_params_ptr)
        OE_SET_OUT_POINTER(encrypted_new_params_ptr, sizeof(unsigned char**), unsigned char***);

    /* Check that in/in-out strings are null terminated. */
    /* There were no in nor in-out string parameters. */

    /* lfence after checks. */
    oe_lfence();

    /* Call user function. */
    enclave_modelaggregator(
        pargs_in->encrypted_accumulator,
        pargs_in->accumulator_lengths,
        pargs_in->accumulator_length,
        pargs_in->encrypted_old_params,
        pargs_in->old_params_length,
        pargs_in->encrypted_new_params_ptr);

    /* Success. */
    _result = OE_OK;
    *output_bytes_written = output_buffer_offset;

done:
    if (output_buffer_size >= sizeof(*pargs_out) &&
        oe_is_within_enclave(pargs_out, output_buffer_size))
        pargs_out->_result = _result;
}

/**** ECALL function table. ****/

oe_ecall_func_t __oe_ecalls_table[] = {
    (oe_ecall_func_t) ecall_enclave_modelaggregator
};

size_t __oe_ecalls_table_size = OE_COUNTOF(__oe_ecalls_table);

/**** OCALL function wrappers. ****/

/* There were no ocalls. */
OE_EXTERNC_END
