/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#ifndef EDGER8R_MODELAGGREGATOR_T_H
#define EDGER8R_MODELAGGREGATOR_T_H

#include <openenclave/enclave.h>

#include "modelaggregator_args.h"

OE_EXTERNC_BEGIN

/**** Trusted function IDs ****/
enum
{
    modelaggregator_fcn_id_enclave_modelaggregator = 0,
    modelaggregator_fcn_id_trusted_call_id_max = OE_ENUM_MAX
};

/**** ECALL marshalling structs. ****/
typedef struct _enclave_modelaggregator_args_t
{
    oe_result_t _result;
    unsigned char*** encrypted_accumulator;
    size_t* accumulator_lengths;
    size_t accumulator_length;
    unsigned char** encrypted_old_params;
    size_t old_params_length;
    unsigned char*** encrypted_new_params_ptr;
} enclave_modelaggregator_args_t;

/**** ECALL prototypes. ****/
void enclave_modelaggregator(
    unsigned char*** encrypted_accumulator,
    size_t* accumulator_lengths,
    size_t accumulator_length,
    unsigned char** encrypted_old_params,
    size_t old_params_length,
    unsigned char*** encrypted_new_params_ptr);

/**** Untrusted function IDs. ****/
enum
{

    modelaggregator_fcn_id_untrusted_call_max = OE_ENUM_MAX
};

/**** OCALL marshalling structs. ****/
/* There were no ocalls. */

/**** OCALL prototypes. ****/
/* There were no ocalls. */

OE_EXTERNC_END

#endif // EDGER8R_MODELAGGREGATOR_T_H
